version: "3.9"

services:
  tests:
    env_file: .env
    # don't write compiled bytecode files (-B) as they mess up the working repo
    command: python -B -m pytest -s -k test_should_be_able_to_analyse_
    # command: sleep inf
    build:
      context: .
    volumes:
      # share the Docker socket for running sibling containers
      - /var/run/docker.sock:/var/run/docker.sock
      # share the source code for live reloading
      - .:/code
      # bind mount /tmp from the host to share the output of the test runner
      - type: bind
        source: ${TMPDIR}
        target: ${TMPDIR}
